version: 2
updates:
- package-ecosystem: npm
  directory: "/tools/cricket_fight_simulator"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
    - 14.14.31
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.21.0
    - 4.22.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.21.0
    - 4.22.0
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.7
    - 1.32.8
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.8.0
    - 7.9.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.4
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.15
    - 7.13.8
  - dependency-name: semver
    versions:
    - 7.3.5
  - dependency-name: parcel-bundler
    versions:
    - 1.12.5
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: vue-eslint-parser
    versions:
    - 7.5.0
    - 7.6.0
  - dependency-name: ant-design-vue
    versions:
    - 1.7.3
    - 1.7.4
