version: 1.0.{build}
image: Visual Studio 2019
pull_requests:
    do_not_increment_build_number: true
branches:
    only:
        - main
environment:
    VERCEL_TOKEN:
        secure: InPNy6LbDQf4YYKZAVYpTbO0uRIKI6D3Dt+nHvOVvS8=
init:
    - ps: Install-Product node lts
    - ps: if ($env:VERCEL_TOKEN) { yarn global add vercel }
build: off
build_script:
    - cmd: dotnet build -c Release /m
artifacts:
    - path: '_publish\**\*.zip'
      name: zip
on_success:
    - ps: if ($env:VERCEL_TOKEN) { $a = vercel _publish --prod -c -C -t $env:VERCEL_TOKEN 2>$1 }
