name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-mods:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.7.2
    - name: Build
      run: dotnet build -c Release /m
    - uses: actions/upload-artifact@v2
      with:
        path: '_publish/**/*.zip'
        if-no-files-found: error
  build-tool:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install
      run: |
        npm install --global yarn
        yarn --version
        yarn global bin
    - name: Build
      run: |
        export PATH="$(yarn global bin):$PATH"
        pushd tools/cricket_fight_simulator
        yarn
        yarn build
        yarn lint
    
    
    
    
    
    
    
    
    
