name: Tool
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  tool:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install
      run: |
        npm install --global yarn
        yarn --version
        yarn global bin
    - name: Build
      run: |
        export PATH="$(yarn global bin):$PATH"
        pushd tools/cricket_fight_simulator
        yarn
        yarn build
        yarn lint
